"""
Convert a raw MOSES capture log (stdout containing `(CAPTURE_CANDIDATE <expr>)`
lines emitted by the temporary hook in scoring/bscore.metta) into a replay
MeTTa file the memo-prototype caching benchmark can iterate over in order.

Usage:
    python3 scripts/capture-to-replay.py <raw.log> <out.replay.metta> [--dedupe-report]
    python3 scripts/capture-to-replay.py <raw.log> <out.replay-quoted.metta> --quote

Extraction: every `(CAPTURE_CANDIDATE ...)` line is located by its literal
prefix, then the following `<expr>` is pulled out with the same stack-based
paren-matching idiom used by `_parse_lisp_results` in scripts/test_moses.py
(count '(' / ')' while scanning characters, close the expression when the
counter returns to 0). No deduplication is performed here: order and
repetition are preserved exactly as they streamed out of the real run,
since repeated candidates are the cache-hit signal the benchmark measures.
"""

import argparse
import re

CAPTURE_PREFIX = "(CAPTURE_CANDIDATE "


def extract_candidates(text):
    """Scan `text` line by line; for every line containing the
    `(CAPTURE_CANDIDATE ` prefix, pull out the single expression that
    follows via stack-based paren matching, then strip the outer
    `(CAPTURE_CANDIDATE ... )` wrapper's own closing paren.

    A CAPTURE_CANDIDATE line has the exact shape:
        (CAPTURE_CANDIDATE <expr>)
    where <expr> is either a bare symbol (e.g. X1) or a fully-parenthesized
    nested expression (e.g. (AND ((NOT (X1)) X2))). We locate the prefix,
    then walk forward: if the next non-space char is '(', use paren-depth
    tracking to find its matching ')'; the expr ends there and the very
    next char must be the CAPTURE_CANDIDATE's own closing ')'. Otherwise
    (bare symbol) walk to the next whitespace-or-')' boundary.
    """
    candidates = []
    idx = 0
    n = len(text)
    while True:
        start = text.find(CAPTURE_PREFIX, idx)
        if start == -1:
            break
        expr_start = start + len(CAPTURE_PREFIX)
        pos = expr_start
        if pos < n and text[pos] == "(":
            depth = 0
            expr_end = None
            for i in range(pos, n):
                c = text[i]
                if c == "(":
                    depth += 1
                elif c == ")":
                    depth -= 1
                    if depth == 0:
                        expr_end = i + 1
                        break
            if expr_end is None:
                # Malformed / truncated line; skip past the prefix and
                # keep scanning rather than looping forever.
                idx = expr_start
                continue
            expr = text[pos:expr_end]
            idx = expr_end
        else:
            # Bare symbol: read until whitespace or an unmatched ')'
            # (the CAPTURE_CANDIDATE wrapper's own close).
            m = re.match(r"\S+", text[pos:])
            token = m.group(0) if m else ""
            # Strip a single trailing ')' that closes CAPTURE_CANDIDATE.
            if token.endswith(")"):
                token = token[:-1]
            expr = token
            idx = pos + len(token)
        candidates.append(expr)
    return candidates


def count_distinct_subtrees(expr):
    """Parse `expr` into nested tuples (bare symbols as leaves) and return
    the set of distinct sub-expressions (as their string form) contained
    within it, including the expression itself. Cheap best-effort parse:
    walks the same paren structure the exprs are already known to have.
    """
    subtrees = set()

    def walk(s):
        subtrees.add(s)
        s = s.strip()
        if not (s.startswith("(") and s.endswith(")")):
            return
        inner = s[1:-1]
        # Split inner into top-level tokens (respecting nested parens).
        depth = 0
        buf = ""
        tokens = []
        for c in inner:
            if c == "(":
                depth += 1
                buf += c
            elif c == ")":
                depth -= 1
                buf += c
                if depth == 0:
                    tokens.append(buf.strip())
                    buf = ""
            elif c == " ":
                if depth == 0:
                    if buf.strip():
                        tokens.append(buf.strip())
                    buf = ""
                else:
                    buf += c
            else:
                buf += c
        if buf.strip():
            tokens.append(buf.strip())
        for t in tokens:
            walk(t)

    walk(expr)
    return subtrees


def write_replay_file(candidates, out_path, quote=False):
    with open(out_path, "w") as f:
        if quote:
            f.write(
                ";; Replay stream generated by scripts/capture-to-replay.py --quote\n"
                ";; from a raw MOSES capture log (see experiments/memo-prototype/).\n"
                ";;\n"
                ";; Order and repetition are preserved exactly as captured -- NO\n"
                ";; deduplication -- because repeated candidates are the cache-hit\n"
                ";; signal the memo-prototype benchmark measures. Each atom carries\n"
                ";; an explicit sequence index because `collapse`-ing a space does\n"
                ";; not guarantee iteration order; the replay driver walks by index.\n"
                ";;\n"
                ";; QUOTED variant (variant P / zipform-nary only): each candidate\n"
                ";; expr is wrapped `(quote <expr>)`. Unlike the plain .replay.metta\n"
                ";; files (whose AND/OR/NOT are inert only because this standalone\n"
                ";; prototype's DEFAULT ops table gives them zero clauses), variant\n"
                ";; P's zipform/ops-nary.metta DOES give AND/OR/NOT real clauses, so\n"
                ";; a bare literal `(AND ...)` occurrence written directly in a file\n"
                ";; that (transitively) imports ops-nary.metta would compile as a\n"
                ";; goal call at translation time (whole-file-prescan rule, see\n"
                ";; zipform/rewriter-nary.metta's header / probes/probe-zip-quote-\n"
                ";; unfired.metta). The `quote` wrapper is the verified fix (see\n"
                ";; probes/probe-nary-quote-store-retrieve.metta): add-atom stores\n"
                ";; the quote-wrapped atom verbatim (never evaluated), and the\n"
                ";; driver retrieves it via a quote-destructuring match pattern,\n"
                ";; `(match &replayStream (candidate $i (quote $e)) $e)`, which\n"
                ";; binds $e to the raw INERT tree -- confirmed by that probe to\n"
                ";; stay inert through let-destructure and through being passed as\n"
                ";; a plain function argument (e.g. into rewriteTreeNaryCached),\n"
                ";; only firing AND/OR/NOT when the evaluator's own per-row\n"
                ";; zipWithN dispatch later calls them deliberately.\n"
                "\n"
                "!(bind! &replayStream (new-space))\n"
            )
        else:
            f.write(
                ";; Replay stream generated by scripts/capture-to-replay.py\n"
                ";; from a raw MOSES capture log (see experiments/memo-prototype/).\n"
                ";;\n"
                ";; Order and repetition are preserved exactly as captured -- NO\n"
                ";; deduplication -- because repeated candidates are the cache-hit\n"
                ";; signal the memo-prototype benchmark measures. Each atom carries\n"
                ";; an explicit sequence index because `collapse`-ing a space does\n"
                ";; not guarantee iteration order; the replay driver walks by index.\n"
                ";;\n"
                ";; The captured expressions are stored as INERT DATA, not wrapped\n"
                ";; in `quote`: in this standalone prototype AND/OR/NOT are not\n"
                ";; defined as functions/equations, so an unquoted (AND ...) /\n"
                ";; (OR ...) / (NOT ...) atom simply fails to reduce to anything\n"
                ";; else and is stored as-is -- quoting would just add a needless\n"
                ";; wrapper the driver would have to strip on every read.\n"
                "\n"
                "!(bind! &replayStream (new-space))\n"
            )
        i = 0
        for c in candidates:
            i += 1
            if quote:
                f.write("!(add-atom &replayStream (candidate {} (quote {})))\n".format(i, c))
            else:
                f.write("!(add-atom &replayStream (candidate {} {}))\n".format(i, c))
        f.write("!(add-atom &replayStream (streamLength {}))\n".format(len(candidates)))


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("raw_log")
    ap.add_argument("out_replay")
    ap.add_argument("--dedupe-report", action="store_true",
                     help="print total/distinct candidate and distinct-subtree counts")
    ap.add_argument("--quote", action="store_true",
                     help="wrap each candidate as (candidate <i> (quote <expr>)) "
                          "instead of storing it bare -- needed for variant-P "
                          "(zipform-nary), whose ops-nary.metta gives AND/OR/NOT "
                          "real clauses (see write_replay_file's --quote comment "
                          "block for why plain storage would misfire there). "
                          "Existing (no-flag) behavior is byte-identical.")
    args = ap.parse_args()

    with open(args.raw_log) as f:
        text = f.read()

    candidates = extract_candidates(text)
    write_replay_file(candidates, args.out_replay, quote=args.quote)

    print("{}: {} candidates -> {}".format(args.raw_log, len(candidates), args.out_replay))

    if args.dedupe_report:
        total = len(candidates)
        distinct = len(set(candidates))
        print("  total candidates:    {}".format(total))
        print("  distinct candidates: {}".format(distinct))
        try:
            distinct_subtrees = set()
            for c in candidates:
                distinct_subtrees |= count_distinct_subtrees(c)
            print("  distinct subtrees:   {}".format(len(distinct_subtrees)))
        except Exception as e:  # best-effort; skip if parsing gets fiddly
            print("  distinct subtrees:   <skipped: {}>".format(e))


if __name__ == "__main__":
    main()
