
name: metta-run CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run Metta setup script
      run: |
        curl -fsSL https://raw.githubusercontent.com/iCog-Labs-Dev/metta-prebuilt-binary/main/install.sh | bash

    - name: move to the metta-run directory
      working-directory: ./metta-run
      run: |
        echo "moved to ./metta-run directory"

    - name: Ensure metta-run is executable
      run: chmod +x $HOME/metta-bin/metta-run
      
    - name: Run tests
      working-directory: ./metta-run
      run: metta-run test

