name: metta-run CI

on:
  push:
    branches: [ref/mettalog]
  pull_request:
    branches: [ref/mettalog]

jobs:
  mettalog-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        set -e
        python -m pip install --upgrade pip
        pip install numpy pyswip janus ansi2html junit2html
        sudo apt-get update
        sudo apt-get install -y swi-prolog
        git clone https://github.com/logicmoo/metta-wam --depth 1
        cd metta-wam
        chmod +x ./INSTALL.sh
        source ./INSTALL.sh --allow-system-modifications
        cd ..

    - name: Run MeTTaLog Tests
      run: |
        mettalog --test examples/tests/unit_test_example.metta
        mettalog --test tests/baseline_compat/metta-morph_tests/tests0.metta
